                      export interface FetalWeekData {
  week: number;
  month: number;
  trimester: 1 | 2 | 3;
  title: string;
  stage: string;
  size: string;
  crownRumpCm: number | null;
  crownHeelCm: number | null;
  weightGrams: number | null;
  heartRateBpm: string | null;
  developments: string[];
  bodyGrowth: string;
  hairGrowth: string;
  sizeComparison: string;
  emoji: string;
  color: string;
}

export const FETAL_DATA: FetalWeekData[] = [
  { week: 1, month: 0.2, trimester: 1, title: "Conception Begins", stage: "Pre-embryo", size: "Microscopic", crownRumpCm: null, crownHeelCm: null, weightGrams: null, heartRateBpm: null, developments: ["Fertilization occurs","Zygote forms","Cell division begins"], bodyGrowth: "Single cell divides into multiple cells", hairGrowth: "None yet", sizeComparison: "Pinhead", emoji: "🔬", color: "#fce4ec" },
  { week: 2, month: 0.5, trimester: 1, title: "Implantation", stage: "Blastocyst", size: "0.1–0.2 mm", crownRumpCm: null, crownHeelCm: null, weightGrams: null, heartRateBpm: null, developments: ["Blastocyst implants in uterus","Placenta begins forming","Amniotic sac starts developing"], bodyGrowth: "Ball of cells embeds in uterine lining", hairGrowth: "None yet", sizeComparison: "Poppy seed", emoji: "🫧", color: "#fce4ec" },
  { week: 3, month: 0.7, trimester: 1, title: "Gastrulation", stage: "Embryo", size: "0.3 mm", crownRumpCm: null, crownHeelCm: null, weightGrams: null, heartRateBpm: null, developments: ["Three germ layers form","Neural plate appears","Primitive streak develops"], bodyGrowth: "Three cell layers differentiate", hairGrowth: "None yet", sizeComparison: "Vanilla seed", emoji: "🧬", color: "#fce4ec" },
  { week: 4, month: 0.9, trimester: 1, title: "Heart Begins to Beat", stage: "Embryo", size: "1–2 mm", crownRumpCm: 0.2, crownHeelCm: null, weightGrams: null, heartRateBpm: "65–80", developments: ["Heart tube forms and beats","Neural tube closing","Limb buds appear"], bodyGrowth: "Heart begins rhythmic contractions", hairGrowth: "None yet", sizeComparison: "Poppy seed", emoji: "💗", color: "#f8bbd0" },
  { week: 5, month: 1.2, trimester: 1, title: "Brain Development", stage: "Embryo", size: "2–3 mm", crownRumpCm: 0.3, crownHeelCm: null, weightGrams: null, heartRateBpm: "100–120", developments: ["Brain vesicles form","Arm and leg buds visible","Optic cups appear"], bodyGrowth: "Brain rapidly dividing into regions", hairGrowth: "None yet", sizeComparison: "Sesame seed", emoji: "🧠", color: "#f8bbd0" },
  { week: 6, month: 1.4, trimester: 1, title: "Facial Features", stage: "Embryo", size: "5–6 mm", crownRumpCm: 0.6, crownHeelCm: null, weightGrams: null, heartRateBpm: "110–140", developments: ["Nose and mouth pits form","Fingers begin to form","Intestines developing"], bodyGrowth: "Face taking shape with eye, ear, nose pits", hairGrowth: "None yet", sizeComparison: "Lentil", emoji: "👶", color: "#f8bbd0" },
  { week: 7, month: 1.6, trimester: 1, title: "Limb Growth", stage: "Embryo", size: "10 mm", crownRumpCm: 1.0, crownHeelCm: null, weightGrams: null, heartRateBpm: "140–170", developments: ["Arms and legs lengthening","Liver producing blood cells","Brain growing rapidly"], bodyGrowth: "Limbs elongating with paddle-shaped hands", hairGrowth: "None yet", sizeComparison: "Blueberry", emoji: "🫐", color: "#f8bbd0" },
  { week: 8, month: 1.8, trimester: 1, title: "All Organs Forming", stage: "Embryo", size: "16 mm", crownRumpCm: 1.6, crownHeelCm: null, weightGrams: 1, heartRateBpm: "150–170", developments: ["All major organs initiated","Fingers and toes separating","Eyelids forming"], bodyGrowth: "Embryo has distinct human form", hairGrowth: "None yet", sizeComparison: "Raspberry", emoji: "🍇", color: "#e1bee7" },
  { week: 9, month: 2.1, trimester: 1, title: "Fetal Stage Begins", stage: "Fetus", size: "23 mm", crownRumpCm: 2.3, crownHeelCm: null, weightGrams: 2, heartRateBpm: "155–175", developments: ["Now officially a fetus","Muscles begin contracting","External genitalia forming"], bodyGrowth: "Tiny movements begin (not yet felt)", hairGrowth: "Hair follicles start forming", sizeComparison: "Cherry", emoji: "🍒", color: "#e1bee7" },
  { week: 10, month: 2.3, trimester: 1, title: "Vital Organs Functional", stage: "Fetus", size: "31 mm", crownRumpCm: 3.1, crownHeelCm: null, weightGrams: 4, heartRateBpm: "160–170", developments: ["Kidneys producing urine","Limbs can bend","Tooth buds forming"], bodyGrowth: "Organs maturing rapidly", hairGrowth: "Peach fuzz follicles developing", sizeComparison: "Kumquat", emoji: "🍊", color: "#e1bee7" },
  { week: 11, month: 2.5, trimester: 1, title: "Fingers & Toes", stage: "Fetus", size: "41 mm", crownRumpCm: 4.1, crownHeelCm: null, weightGrams: 7, heartRateBpm: "155–170", developments: ["Individual fingers and toes","Taste buds forming","Diaphragm developing"], bodyGrowth: "Hands can open and close", hairGrowth: "Tiny hair follicles on scalp", sizeComparison: "Fig", emoji: "🫒", color: "#e1bee7" },
  { week: 12, month: 2.8, trimester: 1, title: "Reflexes Developing", stage: "Fetus", size: "54 mm", crownRumpCm: 5.4, crownHeelCm: null, weightGrams: 14, heartRateBpm: "150–170", developments: ["Reflexes emerging (sucking, swallowing)","Bone marrow making white blood cells","Intestines moving into abdomen"], bodyGrowth: "Skeletal system hardening", hairGrowth: "Fine hair beginning on body", sizeComparison: "Lime", emoji: "🍋", color: "#c5e1a5" },
  { week: 13, month: 3.0, trimester: 1, title: "End of First Trimester", stage: "Fetus", size: "65 mm", crownRumpCm: 6.5, crownHeelCm: null, weightGrams: 23, heartRateBpm: "145–165", developments: ["Vocal cords forming","Fingerprints developing","Intestines absorb nutrients"], bodyGrowth: "Body growing faster than head", hairGrowth: "Lanugo hair appearing", sizeComparison: "Peapod", emoji: "🫛", color: "#c5e1a5" },
  { week: 14, month: 3.2, trimester: 2, title: "Second Trimester Begins", stage: "Fetus", size: "85 mm", crownRumpCm: 8.5, crownHeelCm: null, weightGrams: 43, heartRateBpm: "140–160", developments: ["Facial expressions possible","Sucking reflex active","Kidneys producing urine"], bodyGrowth: "Body proportions becoming more normal", hairGrowth: "Lanugo covers the body", sizeComparison: "Lemon", emoji: "🍋", color: "#a5d6a7" },
  { week: 15, month: 3.5, trimester: 2, title: "Bones Hardening", stage: "Fetus", size: "10 cm", crownRumpCm: 10.0, crownHeelCm: null, weightGrams: 70, heartRateBpm: "140–155", developments: ["Skeleton ossifying","Can sense bright light","Taste buds maturing"], bodyGrowth: "Legs now longer than arms", hairGrowth: "Eyebrows forming", sizeComparison: "Apple", emoji: "🍎", color: "#a5d6a7" },
  { week: 16, month: 3.7, trimester: 2, title: "Facial Muscles Active", stage: "Fetus", size: "11.5 cm", crownRumpCm: 11.5, crownHeelCm: null, weightGrams: 100, heartRateBpm: "140–155", developments: ["Can make facial expressions","Nervous system active","Circulatory system functional"], bodyGrowth: "Muscles and bones strengthening", hairGrowth: "Scalp hair pattern established", sizeComparison: "Avocado", emoji: "🥑", color: "#a5d6a7" },
  { week: 17, month: 3.9, trimester: 2, title: "Fat Begins Forming", stage: "Fetus", size: "13 cm", crownRumpCm: 13.0, crownHeelCm: null, weightGrams: 140, heartRateBpm: "135–155", developments: ["Brown fat depositing","Sweat glands forming","Umbilical cord strengthening"], bodyGrowth: "Adipose tissue starting to form", hairGrowth: "Lanugo thickening", sizeComparison: "Pear", emoji: "🍐", color: "#81c784" },
  { week: 18, month: 4.2, trimester: 2, title: "Baby Can Hear", stage: "Fetus", size: "14 cm", crownRumpCm: 14.0, crownHeelCm: 20.0, weightGrams: 190, heartRateBpm: "135–150", developments: ["Ears functional — can hear sounds","Myelin coating nerves","Vernix caseosa forming"], bodyGrowth: "Ears in final position", hairGrowth: "Vernix (waxy coating) covers skin", sizeComparison: "Bell pepper", emoji: "🫑", color: "#81c784" },
  { week: 19, month: 4.4, trimester: 2, title: "Senses Developing", stage: "Fetus", size: "15 cm", crownRumpCm: 15.0, crownHeelCm: 22.0, weightGrams: 240, heartRateBpm: "130–150", developments: ["Brain designating sensory areas","Arms & legs proportional","Kidneys making urine"], bodyGrowth: "Limbs in correct proportion", hairGrowth: "Scalp hair visible on ultrasound", sizeComparison: "Mango", emoji: "🥭", color: "#81c784" },
  { week: 20, month: 4.6, trimester: 2, title: "Halfway Point!", stage: "Fetus", size: "16 cm", crownRumpCm: 16.0, crownHeelCm: 25.0, weightGrams: 300, heartRateBpm: "130–150", developments: ["Halfway through pregnancy","Can swallow amniotic fluid","Meconium forming in intestines"], bodyGrowth: "Regular sleep/wake cycles forming", hairGrowth: "Hair and nails growing", sizeComparison: "Banana", emoji: "🍌", color: "#66bb6a" },
  { week: 21, month: 4.8, trimester: 2, title: "Movement Patterns", stage: "Fetus", size: "27 cm", crownRumpCm: 18.0, crownHeelCm: 27.0, weightGrams: 360, heartRateBpm: "130–150", developments: ["Coordinated movement patterns","Bone marrow producing blood cells","Eyelids fully formed"], bodyGrowth: "Movements strong enough to feel", hairGrowth: "Eyebrows and lashes present", sizeComparison: "Carrot", emoji: "🥕", color: "#66bb6a" },
  { week: 22, month: 5.1, trimester: 2, title: "Eyes Forming", stage: "Fetus", size: "28 cm", crownRumpCm: 19.0, crownHeelCm: 28.0, weightGrams: 430, heartRateBpm: "130–145", developments: ["Eyelids and eyebrows visible","Lips becoming distinct","Lungs developing branches"], bodyGrowth: "Looking more like a newborn", hairGrowth: "Lanugo covers entire body", sizeComparison: "Papaya", emoji: "🥥", color: "#66bb6a" },
  { week: 23, month: 5.3, trimester: 2, title: "Rapid Brain Growth", stage: "Fetus", size: "29 cm", crownRumpCm: 20.0, crownHeelCm: 29.0, weightGrams: 500, heartRateBpm: "125–145", developments: ["Brain growing rapidly","Can recognize mother's voice","Lungs practicing breathing"], bodyGrowth: "Skin becoming less transparent", hairGrowth: "Hair darkening with pigment", sizeComparison: "Grapefruit", emoji: "🍊", color: "#42a5f5" },
  { week: 24, month: 5.5, trimester: 2, title: "Viability Milestone", stage: "Fetus", size: "30 cm", crownRumpCm: 21.0, crownHeelCm: 30.0, weightGrams: 600, heartRateBpm: "125–145", developments: ["Lungs producing surfactant","Inner ear fully developed","Real hair growing on head"], bodyGrowth: "Taste buds fully functional", hairGrowth: "Real hair growing, lanugo shedding", sizeComparison: "Corn on the cob", emoji: "🌽", color: "#42a5f5" },
  { week: 25, month: 5.8, trimester: 2, title: "Startle Reflex", stage: "Fetus", size: "34 cm", crownRumpCm: 22.0, crownHeelCm: 34.0, weightGrams: 660, heartRateBpm: "125–140", developments: ["Startle reflex active","Nostrils opening","Spine structures forming"], bodyGrowth: "Body fat increasing", hairGrowth: "Hair texture and color developing", sizeComparison: "Cauliflower", emoji: "🥦", color: "#42a5f5" },
  { week: 26, month: 6.0, trimester: 2, title: "Eyes Opening", stage: "Fetus", size: "35 cm", crownRumpCm: 23.0, crownHeelCm: 35.0, weightGrams: 760, heartRateBpm: "120–140", developments: ["Eyes open for the first time","Immune system developing","Can respond to touch"], bodyGrowth: "Lungs developing air sacs", hairGrowth: "Eyelashes fully formed", sizeComparison: "Zucchini", emoji: "🥒", color: "#42a5f5" },
  { week: 27, month: 6.2, trimester: 2, title: "End of Second Trimester", stage: "Fetus", size: "36 cm", crownRumpCm: 24.0, crownHeelCm: 36.0, weightGrams: 875, heartRateBpm: "120–140", developments: ["Regular sleep/wake cycles","Can hiccup","Thalamus brain region active"], bodyGrowth: "Lungs still maturing", hairGrowth: "Full head of hair possible", sizeComparison: "Head of lettuce", emoji: "🥬", color: "#64b5f6" },
  { week: 28, month: 6.5, trimester: 3, title: "Third Trimester Begins", stage: "Fetus", size: "37 cm", crownRumpCm: 25.0, crownHeelCm: 37.0, weightGrams: 1000, heartRateBpm: "120–140", developments: ["Can blink and dream (REM sleep)","Brain surface developing folds","Body temperature regulation starting"], bodyGrowth: "Weight gain accelerating", hairGrowth: "Lanugo starting to disappear", sizeComparison: "Eggplant", emoji: "🍆", color: "#90caf9" },
  { week: 29, month: 6.7, trimester: 3, title: "Muscles Strengthening", stage: "Fetus", size: "38 cm", crownRumpCm: 26.0, crownHeelCm: 38.0, weightGrams: 1150, heartRateBpm: "120–140", developments: ["Muscles and lungs maturing","Bones fully developed but soft","Head growing for brain"], bodyGrowth: "Kicking and stretching strongly", hairGrowth: "Head hair thickening", sizeComparison: "Butternut squash", emoji: "🎃", color: "#90caf9" },
  { week: 30, month: 6.9, trimester: 3, title: "Brain Wrinkles Forming", stage: "Fetus", size: "39 cm", crownRumpCm: 27.0, crownHeelCm: 39.0, weightGrams: 1300, heartRateBpm: "120–140", developments: ["Brain developing wrinkles (gyri)","Bone marrow fully producing blood","Can grasp firmly"], bodyGrowth: "Body fat now 8% of weight", hairGrowth: "Lanugo thinning significantly", sizeComparison: "Cabbage", emoji: "🥬", color: "#90caf9" },
  { week: 31, month: 7.2, trimester: 3, title: "Five Senses Active", stage: "Fetus", size: "41 cm", crownRumpCm: 28.0, crownHeelCm: 41.0, weightGrams: 1500, heartRateBpm: "120–140", developments: ["All five senses functional","Brain connections multiplying","Can process information"], bodyGrowth: "Rapid weight gain period", hairGrowth: "Nails reach fingertips", sizeComparison: "Coconut", emoji: "🥥", color: "#64b5f6" },
  { week: 32, month: 7.4, trimester: 3, title: "Practicing Breathing", stage: "Fetus", size: "42 cm", crownRumpCm: 29.0, crownHeelCm: 42.0, weightGrams: 1700, heartRateBpm: "115–135", developments: ["Practice breathing movements","Toenails visible","Soft downy body hair gone"], bodyGrowth: "Skin thickening and smoothing", hairGrowth: "Most lanugo gone, real hair remains", sizeComparison: "Jicama", emoji: "🍠", color: "#64b5f6" },
  { week: 33, month: 7.6, trimester: 3, title: "Immune System Boost", stage: "Fetus", size: "43 cm", crownRumpCm: 30.0, crownHeelCm: 43.0, weightGrams: 1900, heartRateBpm: "115–135", developments: ["Antibodies transferring from mother","Pupils can constrict and dilate","Bones hardening except skull"], bodyGrowth: "Immune system strengthening", hairGrowth: "Hair growing thicker", sizeComparison: "Pineapple", emoji: "🍍", color: "#64b5f6" },
  { week: 34, month: 7.8, trimester: 3, title: "Lung Maturation", stage: "Fetus", size: "45 cm", crownRumpCm: 32.0, crownHeelCm: 45.0, weightGrams: 2100, heartRateBpm: "115–135", developments: ["Lungs nearly mature","Central nervous system maturing","Fat layer insulating body"], bodyGrowth: "Vernix caseosa thickening", hairGrowth: "Fingernails past fingertips", sizeComparison: "Cantaloupe", emoji: "🍈", color: "#7986cb" },
  { week: 35, month: 8.1, trimester: 3, title: "Rapid Weight Gain", stage: "Fetus", size: "46 cm", crownRumpCm: 33.0, crownHeelCm: 46.0, weightGrams: 2400, heartRateBpm: "115–130", developments: ["Kidneys fully developed","Liver can process waste","Less room to move"], bodyGrowth: "Gaining ~200g per week", hairGrowth: "Full head of hair common", sizeComparison: "Honeydew melon", emoji: "🍈", color: "#7986cb" },
  { week: 36, month: 8.3, trimester: 3, title: "Head Down Position", stage: "Fetus", size: "47 cm", crownRumpCm: 34.0, crownHeelCm: 47.0, weightGrams: 2600, heartRateBpm: "115–130", developments: ["Usually moves head-down","Immune system ready","Digestive system nearly ready"], bodyGrowth: "Skin smooth and soft", hairGrowth: "Lanugo almost entirely gone", sizeComparison: "Romaine lettuce", emoji: "🥬", color: "#7986cb" },
  { week: 37, month: 8.5, trimester: 3, title: "Early Term", stage: "Fetus", size: "48 cm", crownRumpCm: 35.0, crownHeelCm: 48.0, weightGrams: 2900, heartRateBpm: "110–130", developments: ["Considered early term","Practicing inhaling/exhaling","Firm grasp reflex"], bodyGrowth: "All organs mature except lungs and brain", hairGrowth: "Toenails fully formed", sizeComparison: "Winter melon", emoji: "🍉", color: "#9575cd" },
  { week: 38, month: 8.8, trimester: 3, title: "Full Term Approaching", stage: "Fetus", size: "49 cm", crownRumpCm: 35.0, crownHeelCm: 49.0, weightGrams: 3100, heartRateBpm: "110–130", developments: ["Brain and lungs still maturing","All other systems ready","Tear ducts developed"], bodyGrowth: "Body fat ~15% of total weight", hairGrowth: "Hair up to 3.5 cm long", sizeComparison: "Leek", emoji: "🥒", color: "#9575cd" },
  { week: 39, month: 9.0, trimester: 3, title: "Full Term!", stage: "Full-term", size: "50 cm", crownRumpCm: 36.0, crownHeelCm: 50.0, weightGrams: 3300, heartRateBpm: "110–130", developments: ["Officially full term","Chest more prominent","Placenta providing antibodies"], bodyGrowth: "Lungs mature — ready to breathe", hairGrowth: "Vernix mostly shed", sizeComparison: "Watermelon", emoji: "🍉", color: "#7e57c2" },
  { week: 40, month: 9.2, trimester: 3, title: "Due Date", stage: "Full-term", size: "51 cm", crownRumpCm: 36.0, crownHeelCm: 51.0, weightGrams: 3500, heartRateBpm: "110–130", developments: ["Due date week","All systems go","Ready to meet the world"], bodyGrowth: "Average 3.5 kg, 51 cm long", hairGrowth: "Variable — bald to full head of hair", sizeComparison: "Small pumpkin", emoji: "🎃", color: "#7e57c2" },
  { week: 41, month: 9.5, trimester: 3, title: "Post-Due Date", stage: "Late-term", size: "51+ cm", crownRumpCm: 37.0, crownHeelCm: 52.0, weightGrams: 3600, heartRateBpm: "110–130", developments: ["Post-due — monitoring needed","Continued brain development","Nails may be long"], bodyGrowth: "Still growing, less amniotic fluid", hairGrowth: "Nails may need trimming at birth", sizeComparison: "Pumpkin", emoji: "🎃", color: "#6a1b9a" },
];

export const TRIMESTER_RANGES = [
  { label: "1st Trimester", range: [1, 13] as const, color: "#ec4899" },
  { label: "2nd Trimester", range: [14, 27] as const, color: "#22c55e" },
  { label: "3rd Trimester", range: [28, 41] as const, color: "#3b82f6" },
];
