export interface FetalWeekData {
  week: number;
  month: number;
  trimester: 1 | 2 | 3;
  title: string;
  stage: string;
  size: string;
  crownRumpCm: number | null;
  crownHeelCm: number | null;
  weightGrams: number | null;
  heartRateBpm: string | null;
  developments: string[];
  bodyGrowth: string;
  hairGrowth: string;
  sizeComparison: string;
  emoji: string;
  color: string;
  image: string;
}

export const FETAL_DATA: FetalWeekData[] = [
  { week: 1, month: 0.2, trimester: 1, title: "Conception Begins", stage: "Pre-embryo", size: "Microscopic", crownRumpCm: null, crownHeelCm: null, weightGrams: null, heartRateBpm: null, developments: ["Fertilization occurs", "Zygote forms", "Cell division begins"], bodyGrowth: "Single cell divides into multiple cells", hairGrowth: "None yet", sizeComparison: "Pinhead", emoji: "🔬", color: "#d04f51", image: "/images/w1.jpg" },
  { week: 2, month: 0.5, trimester: 1, title: "Fertilization", stage: "Blastocyst", size: "0.1–0.2 mm", crownRumpCm: null, crownHeelCm: null, weightGrams: null, heartRateBpm: null, developments: ["At the start of this week, you ovulate.", "Your egg is fertilized 12 to 24 hours later if a sperm penetrates it.", "The fertilized egg (zygote) starts dividing into multiple cells."], bodyGrowth: "Travels down fallopian tube to uterus.", hairGrowth: "None yet", sizeComparison: "Poppy seed", emoji: "🫧", color: "#d04f51", image: "/images/grow/w1.jpg" },
  { week: 3, month: 0.7, trimester: 1, title: "Implantation", stage: "Embryo", size: "0.3 mm", crownRumpCm: null, crownHeelCm: null, weightGrams: null, heartRateBpm: null, developments: ["Nestled in the nutrient-rich lining of your uterus.", "Microscopic ball of hundreds of rapidly multiplying cells.", "Blastocyst produces the pregnancy hormone hCG."], bodyGrowth: "Ball of cells develops into your baby.", hairGrowth: "None yet", sizeComparison: "Vanilla seed", emoji: "🧬", color: "#d04f51", image: "/images/grow/w3.jpg" },
  { week: 4, month: 0.9, trimester: 1, title: "Heart Begins to Beat", stage: "Embryo", size: "1–2 mm", crownRumpCm: 0.2, crownHeelCm: null, weightGrams: null, heartRateBpm: "65–80", developments: ["Your ball of cells is now officially an embryo.", "About 4 weeks from the beginning of your last period.", "You might be able to get a positive result on a home pregnancy test."], bodyGrowth: "Heart begins rhythmic contractions", hairGrowth: "None yet", sizeComparison: "Poppy seed", emoji: "🫧", color: "#d04f51", image: "/images/grow/w4.jpg" },
  { week: 5, month: 1.2, trimester: 1, title: "Brain Development", stage: "Embryo", size: "2–3 mm", crownRumpCm: 0.3, crownHeelCm: null, weightGrams: null, heartRateBpm: "100–120", developments: ["Your baby resembles a tadpole more than a human.", "The circulatory system is beginning to form.", "Cells in the tiny heart will start to flicker this week."], bodyGrowth: "Brain rapidly dividing into regions", hairGrowth: "None yet", sizeComparison: "Sesame seed", emoji: "🫘", color: "#d04f51", image: "/images/grow/w5.jpg" },
  { week: 6, month: 1.4, trimester: 1, title: "Facial Features", stage: "Embryo", size: "5–6 mm", crownRumpCm: 0.6, crownHeelCm: null, weightGrams: null, heartRateBpm: "110–140", developments: ["Nose, mouth and ears are starting to take shape.", "Intestines are beginning to develop.", "Brain is beginning to develop."], bodyGrowth: "Face taking shape with eye, ear, nose pits", hairGrowth: "None yet", sizeComparison: "Lentil", emoji: "🫘", color: "#d04f51", image: "/images/grow/w6.jpg" },
  { week: 7, month: 1.6, trimester: 1, title: "Limb Growth", stage: "Embryo", size: "10 mm", crownRumpCm: 1.0, crownHeelCm: null, weightGrams: null, heartRateBpm: "140–170", developments: ["Baby has doubled in size since last week.", "Embryonic tail will soon disappear.", "Little hands and feet that look like paddles are emerging."], bodyGrowth: "Limbs elongating with paddle-shaped hands", hairGrowth: "None yet", sizeComparison: "Blueberry", emoji: "🫐", color: "#d04f51", image: "/images/grow/w7.jpg" },
  { week: 8, month: 1.8, trimester: 1, title: "All Organs Forming", stage: "Embryo", size: "16 mm", crownRumpCm: 1.6, crownHeelCm: null, weightGrams: 1, heartRateBpm: "150–170", developments: ["Baby has started moving around.", "Nerve cells are branching out, forming neural pathways.", "Breathing tubes now extend from throat to developing lungs."], bodyGrowth: "Embryo has distinct human form", hairGrowth: "None yet", sizeComparison: "Raspberry", emoji: "🍓", color: "#d04f51", image: "/images/grow/w8.jpg" },
  { week: 9, month: 2.1, trimester: 1, title: "Fetal Stage Begins", stage: "Fetus", size: "23 mm", crownRumpCm: 2.3, crownHeelCm: null, weightGrams: 2, heartRateBpm: "155–175", developments: ["Basic anatomy is developing (even tiny earlobes now).", "Embryonic tail has disappeared.", "About to start gaining weight fast."], bodyGrowth: "Tiny movements begin (not yet felt)", hairGrowth: "Hair follicles start forming", sizeComparison: "Grape", emoji: "🍇", color: "#d04f51", image: "/images/grow/w9.jpg" },
  { week: 10, month: 2.3, trimester: 1, title: "Vital Organs Functional", stage: "Fetus", size: "31 mm", crownRumpCm: 3.1, crownHeelCm: null, weightGrams: 4, heartRateBpm: "160–170", developments: ["Embryo has completed the most critical portion of development.", "Skin is still translucent.", "Tiny limbs can bend and fine details like nails are starting to form."], bodyGrowth: "Organs maturing rapidly", hairGrowth: "Peach fuzz follicles developing", sizeComparison: "Strawberry", emoji: "🍓", color: "#d04f51", image: "/images/grow/w10.jpg" },
  { week: 11, month: 2.5, trimester: 1, title: "Fingers & Toes", stage: "Fetus", size: "41 mm", crownRumpCm: 4.1, crownHeelCm: null, weightGrams: 7, heartRateBpm: "155–170", developments: ["Your baby is almost fully formed.", "They're kicking, stretching, and even hiccupping.", "Diaphragm is developing, although you can't feel any activity yet."], bodyGrowth: "Hands can open and close", hairGrowth: "Tiny hair follicles on scalp", sizeComparison: "Fig", emoji: "🫒", color: "#d04f51", image: "/images/grow/w12.jpg" },
  { week: 12, month: 2.8, trimester: 1, title: "Reflexes Developing", stage: "Fetus", size: "54 mm", crownRumpCm: 5.4, crownHeelCm: null, weightGrams: 14, heartRateBpm: "150–170", developments: ["Reflexes kick in.", "Fingers will soon begin to open and close.", "Toes will curl, and mouth will make sucking movements."], bodyGrowth: "Skeletal system hardening", hairGrowth: "Fine hair beginning on body", sizeComparison: "Lime", emoji: "🍋", color: "#d04f51", image: "/images/grow/w12.jpg" },
  { week: 13, month: 3.0, trimester: 1, title: "End of First Trimester", stage: "Fetus", size: "65 mm", crownRumpCm: 6.5, crownHeelCm: null, weightGrams: 23, heartRateBpm: "145–165", developments: ["Baby's tiny fingers now have fingerprints.", "Veins and organs are clearly visible through the skin.", "If having a girl, ovaries contain more than 2 million eggs."], bodyGrowth: "Body growing faster than head", hairGrowth: "Lanugo hair appearing", sizeComparison: "Plum", emoji: "🍑", color: "#d04f51", image: "/images/grow/w13.jpg" },
  { week: 14, month: 3.2, trimester: 2, title: "Second Trimester Begins", stage: "Fetus", size: "85 mm", crownRumpCm: 8.5, crownHeelCm: null, weightGrams: 43, heartRateBpm: "140–160", developments: ["Brain impulses have begun to fire.", "Using their facial muscles.", "Kidneys are working now, too."], bodyGrowth: "May be seen sucking their thumb on ultrasound", hairGrowth: "Lanugo covers the body", sizeComparison: "Lemon", emoji: "🍋", color: "#a5d6a7", image: "/images/grow/w14.jpg" },
  { week: 15, month: 3.5, trimester: 2, title: "Bones Hardening", stage: "Fetus", size: "10 cm", crownRumpCm: 10.0, crownHeelCm: null, weightGrams: 70, heartRateBpm: "140–155", developments: ["Eyelids are still fused shut, but they can sense light.", "Will move away from a flashlight beam on your tummy.", "Ultrasounds done this week may reveal baby's sex."], bodyGrowth: "Legs now longer than arms", hairGrowth: "Eyebrows forming", sizeComparison: "Apple", emoji: "🍎", color: "#a5d6a7", image: "/images/grow/w15.jpg" },
  { week: 16, month: 3.7, trimester: 2, title: "Facial Muscles Active", stage: "Fetus", size: "11.5 cm", crownRumpCm: 11.5, crownHeelCm: null, weightGrams: 100, heartRateBpm: "140–155", developments: ["Patterning on your baby's scalp has begun.", "Hair isn't visible yet.", "Legs are more developed and head is more upright.", "Ears are close to their final position."], bodyGrowth: "Muscles and bones strengthening", hairGrowth: "Scalp hair pattern established", sizeComparison: "Avocado", emoji: "🥑", color: "#a5d6a7", image: "/images/grow/w16.jpg" },
  { week: 17, month: 3.9, trimester: 2, title: "Fat Begins Forming", stage: "Fetus", size: "13 cm", crownRumpCm: 13.0, crownHeelCm: null, weightGrams: 140, heartRateBpm: "135–155", developments: ["Baby can move their joints.", "Skeleton (formerly soft cartilage) is now hardening to bone.", "Umbilical cord is growing stronger and thicker."], bodyGrowth: "Adipose tissue starting to form", hairGrowth: "Lanugo thickening", sizeComparison: "Turnip", emoji: "🧅", color: "#81c784", image: "/images/grow/w16.jpg" },
  { week: 18, month: 4.2, trimester: 2, title: "Baby Can Hear", stage: "Fetus", size: "14 cm", crownRumpCm: 14.0, crownHeelCm: 20.0, weightGrams: 190, heartRateBpm: "135–150", developments: ["Flexing their arms and legs (you may feel movements).", "Protective coating of myelin forming around nerves."], bodyGrowth: "Ears in final position", hairGrowth: "Vernix (waxy coating) covers skin", sizeComparison: "Bell pepper", emoji: "🫑", color: "#81c784", image: "/images/grow/w16.jpg" },
  { week: 19, month: 4.4, trimester: 2, title: "Senses Developing", stage: "Fetus", size: "15 cm", crownRumpCm: 15.0, crownHeelCm: 22.0, weightGrams: 240, heartRateBpm: "130–150", developments: ["Senses – smell, vision, touch, taste and hearing – are developing.", "They may be able to hear your voice."], bodyGrowth: "Limbs in correct proportion", hairGrowth: "Scalp hair visible on ultrasound", sizeComparison: "Pomegranate", emoji: "🍎", color: "#81c784", image: "/images/grow/w16.jpg" },
  { week: 20, month: 4.6, trimester: 2, title: "Halfway Point!", stage: "Fetus", size: "16 cm", crownRumpCm: 16.0, crownHeelCm: 25.0, weightGrams: 300, heartRateBpm: "130–150", developments: ["Baby can swallow now.", "Digestive system is producing meconium (first poop)."], bodyGrowth: "Regular sleep/wake cycles forming", hairGrowth: "Hair and nails growing", sizeComparison: "Banana", emoji: "🍌", color: "#66bb6a", image: "/images/grow/w16.jpg" },
  { week: 21, month: 4.8, trimester: 2, title: "Movement Patterns", stage: "Fetus", size: "27 cm", crownRumpCm: 18.0, crownHeelCm: 27.0, weightGrams: 360, heartRateBpm: "130–150", developments: ["Movements have gone from flutters to full-on kicks and jabs.", "You may start to notice patterns in their activity."], bodyGrowth: "Movements strong enough to feel", hairGrowth: "Eyebrows and lashes present", sizeComparison: "Mango", emoji: "🥭", color: "#66bb6a", image: "/images/grow/w16.jpg" },
  { week: 22, month: 5.1, trimester: 2, title: "Eyes Forming", stage: "Fetus", size: "28 cm", crownRumpCm: 19.0, crownHeelCm: 28.0, weightGrams: 430, heartRateBpm: "130–145", developments: ["Looks almost like a miniature newborn.", "Features such as lips and eyebrows are more distinct.", "Eye pigment isn't present yet."], bodyGrowth: "Looking more like a newborn", hairGrowth: "Lanugo covers entire body", sizeComparison: "Sweet potato", emoji: "🍠", color: "#66bb6a", image: "/images/grow/w22.jpg" },
  { week: 23, month: 5.3, trimester: 2, title: "Rapid Brain Growth", stage: "Fetus", size: "29 cm", crownRumpCm: 20.0, crownHeelCm: 29.0, weightGrams: 500, heartRateBpm: "125–145", developments: ["Ears are getting better at picking up sounds.", "May recognize some noises outside the womb after birth."], bodyGrowth: "Skin becoming less transparent", hairGrowth: "Hair darkening with pigment", sizeComparison: "Grapefruit", emoji: "🍊", color: "#42a5f5", image: "/images/grow/w22.jpg" },
  { week: 24, month: 5.5, trimester: 2, title: "Viability Milestone", stage: "Fetus", size: "30 cm", crownRumpCm: 21.0, crownHeelCm: 30.0, weightGrams: 600, heartRateBpm: "125–145", developments: ["Cuts a pretty long and lean figure, but chubbier times are coming.", "Skin is still thin and translucent, but will change soon."], bodyGrowth: "Taste buds fully functional", hairGrowth: "Real hair growing, lanugo shedding", sizeComparison: "Ear of corn", emoji: "🌽", color: "#42a5f5", image: "/images/grow/w24.jpg" },
  { week: 25, month: 5.8, trimester: 2, title: "Startle Reflex", stage: "Fetus", size: "34 cm", crownRumpCm: 22.0, crownHeelCm: 34.0, weightGrams: 660, heartRateBpm: "125–140", developments: ["Wrinkled skin is starting to fill out with baby fat.", "Hair is beginning to come in, with color and texture."], bodyGrowth: "Body fat increasing", hairGrowth: "Hair texture and color developing", sizeComparison: "Acorn squash", emoji: "🍈", color: "#42a5f5", image: "/images/grow/w24.jpg" },
  { week: 26, month: 6.0, trimester: 2, title: "Eyes Opening", stage: "Fetus", size: "35 cm", crownRumpCm: 23.0, crownHeelCm: 35.0, weightGrams: 760, heartRateBpm: "120–140", developments: ["Inhaling and exhaling amniotic fluid (helps lung development).", "Breathing movements are good practice for that first breath of air."], bodyGrowth: "Lungs developing air sacs", hairGrowth: "Eyelashes fully formed", sizeComparison: "Spaghetti squash", emoji: "🍈", color: "#42a5f5", image: "/images/grow/w24.jpg" },
  { week: 27, month: 6.2, trimester: 2, title: "End of Second Trimester", stage: "Fetus", size: "36 cm", crownRumpCm: 24.0, crownHeelCm: 36.0, weightGrams: 875, heartRateBpm: "120–140", developments: ["Sleeps and wakes on a regular schedule.", "Brain is very active.", "Could function outside the womb with medical help."], bodyGrowth: "Lungs still maturing", hairGrowth: "Full head of hair possible", sizeComparison: "Head of cauliflower", emoji: "🥦", color: "#64b5f6", image: "/images/grow/w27.jpg" },
  { week: 28, month: 6.5, trimester: 3, title: "Third Trimester Begins", stage: "Fetus", size: "37 cm", crownRumpCm: 25.0, crownHeelCm: 37.0, weightGrams: 1000, heartRateBpm: "120–140", developments: ["Eyesight is developing (can sense light filtering in).", "Baby can blink.", "Eyelashes have grown in."], bodyGrowth: "Weight gain accelerating", hairGrowth: "Lanugo starting to disappear", sizeComparison: "Large eggplant", emoji: "🍆", color: "#90caf9", image: "/images/grow/w28.jpg" },
  { week: 29, month: 6.7, trimester: 3, title: "Muscles Strengthening", stage: "Fetus", size: "38 cm", crownRumpCm: 26.0, crownHeelCm: 38.0, weightGrams: 1150, heartRateBpm: "120–140", developments: ["Muscles and lungs are busy getting ready to function outside.", "Head is growing to make room for developing brain."], bodyGrowth: "Kicking and stretching strongly", hairGrowth: "Head hair thickening", sizeComparison: "Butternut squash", emoji: "🎃", color: "#90caf9", image: "/images/grow/w28.jpg" },
  { week: 30, month: 6.9, trimester: 3, title: "Brain Wrinkles Forming", stage: "Fetus", size: "39 cm", crownRumpCm: 27.0, crownHeelCm: 39.0, weightGrams: 1300, heartRateBpm: "120–140", developments: ["Surrounded by a pint and a half of amniotic fluid.", "Less fluid as they grow and claim more space."], bodyGrowth: "Body fat now 8% of weight", hairGrowth: "Lanugo thinning significantly", sizeComparison: "Large cabbage", emoji: "🥬", color: "#90caf9", image: "/images/grow/w30.jpg" },
  { week: 31, month: 7.2, trimester: 3, title: "Five Senses Active", stage: "Fetus", size: "41 cm", crownRumpCm: 28.0, crownHeelCm: 41.0, weightGrams: 1500, heartRateBpm: "120–140", developments: ["Can now turn their head from side to side.", "Protective layer of fat is accumulating under skin.", "Fat is filling out their arms and legs."], bodyGrowth: "Rapid weight gain period", hairGrowth: "Nails reach fingertips", sizeComparison: "Coconut", emoji: "🥥", color: "#64b5f6", image: "/images/grow/w30.jpg" },
  { week: 32, month: 7.4, trimester: 3, title: "Practicing Breathing", stage: "Fetus", size: "42 cm", crownRumpCm: 29.0, crownHeelCm: 42.0, weightGrams: 1700, heartRateBpm: "115–135", developments: ["Will gain one-third to half their birth weight in the next seven weeks.", "Preparing for life outside the womb."], bodyGrowth: "Skin thickening and smoothing", hairGrowth: "Most lanugo gone, real hair remains", sizeComparison: "Papaya", emoji: "🥭", color: "#64b5f6", image: "/images/grow/w30.jpg" },
  { week: 33, month: 7.6, trimester: 3, title: "Immune System Boost", stage: "Fetus", size: "43 cm", crownRumpCm: 30.0, crownHeelCm: 43.0, weightGrams: 1900, heartRateBpm: "115–135", developments: ["Bones in the skull aren't fused yet.", "Allows head to shift and squeeze through the birth canal.", "Won't fully fuse until adulthood."], bodyGrowth: "Immune system strengthening", hairGrowth: "Hair growing thicker", sizeComparison: "Pineapple", emoji: "🍍", color: "#64b5f6", image: "/images/grow/w30.jpg" },
  { week: 34, month: 7.8, trimester: 3, title: "Lung Maturation", stage: "Fetus", size: "45 cm", crownRumpCm: 32.0, crownHeelCm: 45.0, weightGrams: 2100, heartRateBpm: "115–135", developments: ["Central nervous system is maturing, as are lungs.", "Babies born between 34 and 37 weeks usually do well."], bodyGrowth: "Vernix caseosa thickening", hairGrowth: "Fingernails past fingertips", sizeComparison: "Cantaloupe", emoji: "🍈", color: "#7986cb", image: "/images/grow/w30.jpg" },
  { week: 35, month: 8.1, trimester: 3, title: "Rapid Weight Gain", stage: "Fetus", size: "46 cm", crownRumpCm: 33.0, crownHeelCm: 46.0, weightGrams: 2400, heartRateBpm: "115–130", developments: ["Getting snug inside your womb, but you should still feel movements.", "Kidneys are fully developed.", "Liver can process some waste products."], bodyGrowth: "Gaining ~200g per week", hairGrowth: "Full head of hair common", sizeComparison: "Honeydew melon", emoji: "🍈", color: "#7986cb", image: "/images/grow/w35.jpg" },
  { week: 36, month: 8.3, trimester: 3, title: "Head Down Position", stage: "Fetus", size: "47 cm", crownRumpCm: 34.0, crownHeelCm: 47.0, weightGrams: 2600, heartRateBpm: "115–130", developments: ["Gaining about an ounce a day.", "Losing most of their lanugo hair.", "Losing the vernix caseosa (waxy substance protecting skin)."], bodyGrowth: "Skin smooth and soft", hairGrowth: "Lanugo almost entirely gone", sizeComparison: "Head of romaine lettuce", emoji: "🥬", color: "#7986cb", image: "/images/grow/w35.jpg" },
  { week: 37, month: 8.5, trimester: 3, title: "Early Term", stage: "Fetus", size: "48 cm", crownRumpCm: 35.0, crownHeelCm: 48.0, weightGrams: 2900, heartRateBpm: "110–130", developments: ["Due date is very close.", "Looks like a newborn, but not considered full-term until 39 weeks.", "Lungs and brain will continue to mature."], bodyGrowth: "All organs mature except lungs and brain", hairGrowth: "Toenails fully formed", sizeComparison: "Bunch of Swiss chard", emoji: "🥬", color: "#9575cd", image: "/images/grow/w35.jpg" },
  { week: 38, month: 8.8, trimester: 3, title: "Full Term Approaching", stage: "Fetus", size: "49 cm", crownRumpCm: 35.0, crownHeelCm: 49.0, weightGrams: 3100, heartRateBpm: "110–130", developments: ["Irises aren't fully pigmented at birth.", "Eyes could change color up until they're about a year old."], bodyGrowth: "Body fat ~15% of total weight", hairGrowth: "Hair up to 3.5 cm long", sizeComparison: "Mini watermelon", emoji: "🍉", color: "#9575cd", image: "/images/grow/w35.jpg" },
  { week: 39, month: 9.0, trimester: 3, title: "Full Term!", stage: "Full-term", size: "50 cm", crownRumpCm: 36.0, crownHeelCm: 50.0, weightGrams: 3300, heartRateBpm: "110–130", developments: ["Physical development is complete.", "Still busy putting on fat and growing bigger."], bodyGrowth: "Lungs mature — ready to breathe", hairGrowth: "Vernix mostly shed", sizeComparison: "Pumpkin", emoji: "🎃", color: "#7e57c2", image: "/images/grow/w35.jpg" },
  { week: 40, month: 9.2, trimester: 3, title: "Due Date", stage: "Full-term", size: "51 cm", crownRumpCm: 36.0, crownHeelCm: 51.0, weightGrams: 3500, heartRateBpm: "110–130", developments: ["If past due date, may not be as late as you think (late ovulation).", "Provider will continuously assess pregnancy to make sure it's safe."], bodyGrowth: "Average 3.5 kg, 51 cm long", hairGrowth: "Variable — bald to full head of hair", sizeComparison: "Watermelon", emoji: "🍉", color: "#7e57c2", image: "/images/grow/w40.jpg" },
  { week: 41, month: 9.5, trimester: 3, title: "Post-Due Date", stage: "Late-term", size: "51+ cm", crownRumpCm: 37.0, crownHeelCm: 52.0, weightGrams: 3600, heartRateBpm: "110–130", developments: ["Considered late-term.", "Provider will probably talk about inducing labor.", "May perform a non-stress test (NST) to monitor fetal heart rate."], bodyGrowth: "Still growing, less amniotic fluid", hairGrowth: "Nails may need trimming at birth", sizeComparison: "Watermelon", emoji: "🍉", color: "#6a1b9a", image: "/images/grow/w40.jpg" },
];;

export const TRIMESTER_RANGES = [
  { label: "1st Trimester", range: [1, 13] as const, color: "#d04f51" },
  { label: "2nd Trimester", range: [14, 27] as const, color: "#22c55e" },
  { label: "3rd Trimester", range: [28, 41] as const, color: "#3b82f6" },
];
