"use client";

import * as React from "react";
import {
  useState,
  useEffect,
  useImperativeHandle,
  forwardRef,
  useCallback,
  useRef,
} from "react";
import {
  IconMessage,
  IconPlus,
  IconTrash,
  IconDots,
  IconInnerShadowTop,
  IconLoader,
} from "@tabler/icons-react";

import {
  Sidebar,
  SidebarContent,
  SidebarFooter,
  SidebarHeader,
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
  SidebarGroup,
  SidebarGroupContent,
  SidebarGroupLabel,
} from "@/components/ui/sidebar";
import { getSession } from "@/lib/authentication";

import { ChatSession as ApiChatSession } from "../app/api/chatbot/types";
import apis from "../app/api/chatbot/api";

interface ChatSession {
  id: number;
  session_id: number;
  session_name: string;
  created_at: string;
  last_activity: string;
  message_count: number;
}

type NormalizableApiChatSession = ApiChatSession & {
  id?: number | string;
  session_id?: number | string;
  session_name?: string | null;
  created_at?: string;
  updated_at?: string;
  last_activity?: string;
  message_count?: number | null;
};

export interface ChatSidebarRef {
  refreshChatHistory: () => Promise<void>;
}

interface ChatSidebarProps extends React.ComponentProps<typeof Sidebar> {
  activeSessionId?: number | null;
  onSessionSelect?: (sessionId: number | null) => void;
}

function getErrorMessage(error: unknown, fallback: string): string {
  if (error instanceof Error) {
    return error.message;
  }

  if (
    typeof error === "object" &&
    error !== null &&
    "message" in error &&
    typeof error.message === "string"
  ) {
    return error.message;
  }

  return fallback;
}

function getDisplayTitle(session: ChatSession) {
  const raw = session.session_name?.trim();

  if (!raw) return "New chat";

  const looksAutoGenerated =
    /^chat\s+\d{4}[-/]\d{1,2}[-/]\d{1,2}/i.test(raw) ||
    /^chat\s+\d{1,2}\/\d{1,2}\/\d{4}/i.test(raw);

  if (looksAutoGenerated) return "New chat";

  return raw.length > 50 ? `${raw.slice(0, 50)}...` : raw;
}

function normalizeSessions(sessions: ApiChatSession[]): ChatSession[] {
  return sessions.map((s: NormalizableApiChatSession) => {
    const canonicalId = Number(s.session_id ?? s.id);

    return {
      ...s,
      id: canonicalId,
      session_id: canonicalId,
      session_name: s.session_name?.trim() || "New chat",
      created_at: s.created_at || "",
      last_activity: s.updated_at || s.last_activity || s.created_at || "",
      message_count: s.message_count ?? 0,
    };
  });
}

function ChatHistoryItem({
  session,
  isActive,
  onSelect,
  onDelete,
}: {
  session: ChatSession;
  isActive?: boolean;
  onSelect: (sessionId: number) => void;
  onDelete: (sessionId: number) => void;
}) {
  const [showOptions, setShowOptions] = useState(false);
  const menuRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    const handleDocumentClick = (e: MouseEvent) => {
      if (menuRef.current && !menuRef.current.contains(e.target as Node)) {
        setShowOptions(false);
      }
    };

    if (showOptions) {
      document.addEventListener("click", handleDocumentClick);
      return () => document.removeEventListener("click", handleDocumentClick);
    }
  }, [showOptions]);

  return (
    <SidebarMenuItem>
      <div
        onClick={() => onSelect(session.id)}
        className={`group relative flex items-center justify-between rounded-lg px-3 py-2 cursor-pointer transition-all duration-200 ${
          isActive
            ? "bg-pink-100 text-gray-900"
            : "text-gray-700 hover:bg-pink-50"
        }`}
      >
        <div className="flex min-w-0 items-center gap-2">
          <IconMessage className="h-4 w-4 text-[#d04f51] flex-shrink-0" />
          <span className="truncate text-sm font-medium">
            {getDisplayTitle(session)}
          </span>
        </div>

        <div className="relative ml-2" ref={menuRef}>
          <button
            onClick={(e) => {
              e.stopPropagation();
              setShowOptions((s) => !s);
            }}
            className="opacity-0 group-hover:opacity-100 p-1 hover:bg-gray-200 rounded transition-opacity"
            type="button"
          >
            <IconDots className="h-4 w-4 text-gray-500" />
          </button>

          {showOptions && (
            <div className="absolute right-0 top-full mt-1 bg-white border border-gray-200 rounded-md shadow-lg z-10 min-w-[120px]">
              <button
                onClick={(e) => {
                  e.stopPropagation();
                  onDelete(session.id);
                  setShowOptions(false);
                }}
                className="flex items-center gap-2 w-full px-3 py-2 text-sm text-red-600 hover:bg-red-50"
                type="button"
              >
                <IconTrash className="h-4 w-4" />
                Delete
              </button>
            </div>
          )}
        </div>
      </div>
    </SidebarMenuItem>
  );
}

export const ChatSidebar = forwardRef<ChatSidebarRef, ChatSidebarProps>(
  ({ activeSessionId, onSessionSelect, ...props }, ref) => {
    const [chatSessions, setChatSessions] = useState<ChatSession[]>([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);
    const [creatingSession, setCreatingSession] = useState(false);
    const [token, setToken] = useState<string | null>(null);

    const ensureToken = useCallback(async (): Promise<string | null> => {
      if (token) return token;

      const session = await getSession();
      const jwt = session?.user?.token || null;

      if (jwt) setToken(jwt);

      return jwt;
    }, [token]);

    const fetchChatSessions = useCallback(async () => {
      const jwt = await ensureToken();

      if (!jwt) {
        setError("Please log in to use the chatbot.");
        setLoading(false);
        return;
      }

      try {
        setLoading(true);
        setError(null);

        const data = await apis.listChats(jwt);

        if (data.status === "success") {
          setChatSessions(normalizeSessions(data.sessions || []));
        } else {
          setError(data.message || "Failed to load chat sessions");
        }
      } catch (e: unknown) {
        setError(getErrorMessage(e, "Unable to connect to server"));
      } finally {
        setLoading(false);
      }
    }, [ensureToken]);

    useImperativeHandle(ref, () => ({
      refreshChatHistory: fetchChatSessions,
    }));

    useEffect(() => {
      const initialize = async () => {
        await ensureToken();
      };
      initialize();
    }, [ensureToken]);

    useEffect(() => {
      if (token) fetchChatSessions();
    }, [token, fetchChatSessions]);

    const handleNewChat = async () => {
      const jwt = await ensureToken();

      if (!jwt) {
        setError("Please log in first");
        return;
      }

      setCreatingSession(true);

      try {
        const data = await apis.createChat(jwt, {
          session_name: "New chat",
        });

        if (data.status === "success") {
          const newSessionId = Number(data.session_id);

          await fetchChatSessions();
          onSessionSelect?.(newSessionId);
        } else {
          setError(data.message || "Failed to create new chat");
        }
      } catch (e: unknown) {
        setError(getErrorMessage(e, "Failed to create new chat"));
      } finally {
        setCreatingSession(false);
      }
    };

    const handleDeleteChat = async (sessionId: number) => {
      const jwt = await ensureToken();

      if (!jwt) {
        setError("Please log in first");
        return;
      }

      if (!confirm("Are you sure you want to delete this chat?")) return;

      try {
        const data = await apis.deleteChat(jwt, sessionId);

        if (data.status === "success") {
          setChatSessions((prev) => prev.filter((s) => s.id !== sessionId));

          if (activeSessionId === sessionId) {
            onSessionSelect?.(null);
          }
        } else {
          setError(data.message || "Failed to delete chat");
        }
      } catch (e: unknown) {
        setError(getErrorMessage(e, "Failed to delete chat"));
      }
    };

    const sortedSessions = [...chatSessions].sort(
      (a, b) =>
        new Date(b.last_activity).getTime() -
        new Date(a.last_activity).getTime()
    );

    return (
      <Sidebar reserveSpace={false} collapsible="offcanvas" {...props}>
        <SidebarHeader>
          <SidebarMenu>
            <SidebarMenuItem>
              <SidebarMenuButton asChild>
                <button type="button" className="flex items-center gap-2">
                  <IconInnerShadowTop className="!size-5 text-[#d04f51]" />
                  <span className="font-semibold bg-[#d04f51] bg-clip-text text-transparent">
                    Mathru AI
                  </span>
                </button>
              </SidebarMenuButton>
            </SidebarMenuItem>
          </SidebarMenu>

          <div className="px-3 py-2">
            <button
              onClick={handleNewChat}
              disabled={creatingSession}
              className="w-full flex items-center gap-3 px-4 py-3 bg-[#d04f51] text-white rounded-lg transition-all duration-200 shadow-md disabled:opacity-50 hover:bg-[#ba4547]"
              type="button"
            >
              {creatingSession ? (
                <IconLoader className="h-5 w-5 animate-spin" />
              ) : (
                <IconPlus className="h-5 w-5" />
              )}
              <span>{creatingSession ? "Creating..." : "New Chat"}</span>
            </button>
          </div>
        </SidebarHeader>

        <SidebarContent className="px-2">
          {error && (
            <div className="mx-3 mb-2 p-2 bg-red-50 border border-red-200 rounded text-xs text-red-600">
              {error}
              <button
                onClick={fetchChatSessions}
                className="ml-2 underline hover:no-underline"
                type="button"
              >
                Retry
              </button>
            </div>
          )}

          <SidebarGroup>
            <SidebarGroupLabel className="text-gray-600 font-medium px-3 py-2 flex items-center justify-between">
              <span>Your chats</span>
              <button
                onClick={fetchChatSessions}
                className="p-1 hover:bg-gray-100 rounded"
                type="button"
              >
                <IconLoader
                  className={`h-3 w-3 text-gray-400 ${
                    loading ? "animate-spin" : ""
                  }`}
                />
              </button>
            </SidebarGroupLabel>

            <SidebarGroupContent className="space-y-1 list-none">
              {loading && (
                <div className="text-center text-gray-500 text-sm py-4">
                  Loading chats...
                </div>
              )}

              {!loading &&
                sortedSessions.map((session) => (
                  <ChatHistoryItem
                    key={session.id}
                    session={session}
                    isActive={session.id === activeSessionId}
                    onSelect={(id) => onSessionSelect?.(id)}
                    onDelete={handleDeleteChat}
                  />
                ))}

              {!loading && chatSessions.length === 0 && (
                <div className="text-center text-gray-500 text-sm py-4">
                  No chat history found.
                </div>
              )}
            </SidebarGroupContent>
          </SidebarGroup>
        </SidebarContent>

        <SidebarFooter className="p-3 text-xs text-gray-400 text-center">
          <span></span>
        </SidebarFooter>
      </Sidebar>
    );
  }
);

ChatSidebar.displayName = "ChatSidebar";