"use client";

import * as React from "react";
import {
  useState,
  useEffect,
  useImperativeHandle,
  forwardRef,
  useCallback,
  useRef,
} from "react";
import {
  IconDots,
  IconLoader,
  IconMessage,
  IconPlus,
  IconTrash,
} from "@tabler/icons-react";

import {
  Sidebar,
  SidebarContent,
  SidebarFooter,
  SidebarHeader,
  SidebarMenu,
  SidebarMenuItem,
  SidebarGroup,
  SidebarGroupContent,
  SidebarGroupLabel,
} from "@/components/ui/sidebar";
import { getSession } from "@/lib/authentication";

import { ChatSession as ApiChatSession } from "../app/api/chatbot/types";
import apis from "../app/api/chatbot/api";
import "../app/(panel)/midwife/dashboard/components/ai-assistant-card.css";

interface ChatSession {
  id: number;
  session_id: number;
  session_name: string;
  created_at: string;
  last_activity: string;
  message_count: number;
}

export interface ChatSidebarRef {
  refreshChatHistory: () => Promise<void>;
}

interface ChatSidebarProps extends React.ComponentProps<typeof Sidebar> {
  activeSessionId?: number | null;
  onSessionSelect?: (sessionId: number | null) => void;
}

function getErrorMessage(error: unknown, fallback: string): string {
  if (error instanceof Error) {
    return error.message;
  }

  if (
    typeof error === "object" &&
    error !== null &&
    "message" in error &&
    typeof error.message === "string"
  ) {
    return error.message;
  }

  return fallback;
}

function getDisplayTitle(session: ChatSession) {
  const raw = session.session_name?.trim();

  if (!raw) return "New chat";

  const looksAutoGenerated =
    /^chat\s+\d{4}[-/]\d{1,2}[-/]\d{1,2}/i.test(raw) ||
    /^chat\s+\d{1,2}\/\d{1,2}\/\d{4}/i.test(raw);

  if (looksAutoGenerated) return "New chat";

  return raw.length > 50 ? `${raw.slice(0, 50)}...` : raw;
}

function normalizeSessions(sessions: ApiChatSession[]): ChatSession[] {
  return sessions.map((s: ApiChatSession) => {
    const canonicalId = Number(s.session_id ?? s.id);

    return {
      ...s,
      id: canonicalId,
      session_id: canonicalId,
      session_name: s.session_name?.trim() || "New chat",
      last_activity: s.updated_at || s.last_activity || s.created_at,
      message_count: s.message_count ?? 0,
    };
  });
}

function ChatHistoryItem({
  session,
  isActive,
  onSelect,
  onDelete,
}: {
  session: ChatSession;
  isActive?: boolean;
  onSelect: (sessionId: number) => void;
  onDelete: (sessionId: number) => void;
}) {
  const [showOptions, setShowOptions] = useState(false);
  const menuRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    const handleDocumentClick = (e: MouseEvent) => {
      if (menuRef.current && !menuRef.current.contains(e.target as Node)) {
        setShowOptions(false);
      }
    };

    if (showOptions) {
      document.addEventListener("click", handleDocumentClick);
      return () => document.removeEventListener("click", handleDocumentClick);
    }
  }, [showOptions]);

  return (
    <SidebarMenuItem>
      <div
        onClick={() => onSelect(session.id)}
        className={`group relative flex w-full cursor-pointer items-center justify-between rounded-2xl border px-3 py-2 transition ${
          isActive
            ? "border-white/10 bg-white/[0.08] text-white"
            : "border-transparent text-white/70 hover:border-white/10 hover:bg-white/[0.04] hover:text-white"
        }`}
      >
        <div className="flex min-w-0 items-center gap-2">
          <div className="flex h-7 w-7 shrink-0 items-center justify-center rounded-xl bg-[#d04f51]/10">
            <IconMessage className="h-3 w-3 text-[#ff7b7d]" />
          </div>

          <div className="min-w-0">
            <p className="truncate text-xs font-medium">
              {getDisplayTitle(session)}
            </p>
            <p className="mt-0.5 text-[10px] text-white/35">
              {session.message_count} messages
            </p>
          </div>
        </div>

        <div className="relative ml-2 shrink-0" ref={menuRef}>
          <button
            onClick={(e) => {
              e.stopPropagation();
              setShowOptions((s) => !s);
            }}
            className="rounded-lg p-1.5 text-white/45 opacity-100 transition hover:bg-white/10 hover:text-white sm:opacity-0 sm:group-hover:opacity-100"
            type="button"
          >
            <IconDots className="h-4 w-4" />
          </button>

          {showOptions && (
            <div className="absolute right-0 top-full z-20 mt-1 min-w-[132px] rounded-xl border border-white/10 bg-[#111111] p-1 shadow-2xl">
              <button
                onClick={(e) => {
                  e.stopPropagation();
                  onDelete(session.id);
                  setShowOptions(false);
                }}
                className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-sm text-red-400 transition hover:bg-red-500/10"
                type="button"
              >
                <IconTrash className="h-4 w-4" />
                Delete
              </button>
            </div>
          )}
        </div>
      </div>
    </SidebarMenuItem>
  );
}

export const ChatSidebarMidwife = forwardRef<ChatSidebarRef, ChatSidebarProps>(
  ({ activeSessionId, onSessionSelect, ...props }, ref) => {
    const [chatSessions, setChatSessions] = useState<ChatSession[]>([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);
    const [creatingSession, setCreatingSession] = useState(false);
    const [token, setToken] = useState<string | null>(null);

    const ensureToken = useCallback(async (): Promise<string | null> => {
      if (token) return token;

      const session = await getSession();
      const jwt = session?.user?.token || null;

      if (jwt) setToken(jwt);

      return jwt;
    }, [token]);

    const fetchChatSessions = useCallback(async () => {
      const jwt = await ensureToken();

      if (!jwt) {
        setError("Please log in to use the chatbot.");
        setLoading(false);
        return;
      }

      try {
        setLoading(true);
        setError(null);

        const data = await apis.listChats(jwt);

        if (data.status === "success") {
          setChatSessions(normalizeSessions(data.sessions || []));
        } else {
          setError(data.message || "Failed to load chat sessions");
        }
      } catch (e: unknown) {
        setError(getErrorMessage(e, "Unable to connect to server"));
      } finally {
        setLoading(false);
      }
    }, [ensureToken]);

    useImperativeHandle(ref, () => ({
      refreshChatHistory: fetchChatSessions,
    }));

    useEffect(() => {
      const initialize = async () => {
        await ensureToken();
      };

      initialize();
    }, [ensureToken]);

    useEffect(() => {
      if (token) fetchChatSessions();
    }, [token, fetchChatSessions]);

    const handleNewChat = async () => {
      const jwt = await ensureToken();

      if (!jwt) {
        setError("Please log in first");
        return;
      }

      setCreatingSession(true);

      try {
        const data = await apis.createChat(jwt, {
          session_name: "New chat",
        });

        if (data.status === "success") {
          const newSessionId = Number(data.session_id);
          await fetchChatSessions();
          onSessionSelect?.(newSessionId);
        } else {
          setError(data.message || "Failed to create new chat");
        }
      } catch (e: unknown) {
        setError(getErrorMessage(e, "Failed to create new chat"));
      } finally {
        setCreatingSession(false);
      }
    };

    const handleDeleteChat = async (sessionId: number) => {
      const jwt = await ensureToken();

      if (!jwt) {
        setError("Please log in first");
        return;
      }

      if (!confirm("Are you sure you want to delete this chat?")) return;

      try {
        const data = await apis.deleteChat(jwt, sessionId);

        if (data.status === "success") {
          setChatSessions((prev) => prev.filter((s) => s.id !== sessionId));

          if (activeSessionId === sessionId) {
            onSessionSelect?.(null);
          }
        } else {
          setError(data.message || "Failed to delete chat");
        }
      } catch (e: unknown) {
        setError(getErrorMessage(e, "Failed to delete chat"));
      }
    };

    const sortedSessions = [...chatSessions].sort(
      (a, b) =>
        new Date(b.last_activity).getTime() -
        new Date(a.last_activity).getTime()
    );

    return (
      <Sidebar
        reserveSpace={true}
        collapsible="offcanvas"
        className="border-r border-white/10 bg-[#050505] text-white w-[88vw] max-w-[320px] lg:w-[320px]"
        {...props}
      >
        <SidebarHeader className="border-b border-white/10 bg-[#080808]">
          <SidebarMenu>
            <SidebarMenuItem>
              <div className="text-left">
                <p className="text-xs text-white/40 text-center">
                  Conversation history
                </p>
              </div>
            </SidebarMenuItem>
          </SidebarMenu>

          <div className="px-3 pb-3">
            <button
              onClick={handleNewChat}
              disabled={creatingSession}
              type="button"
              className="flex w-full items-center justify-center gap-3 rounded-2xl bg-[#d04f51] px-3 py-2 text-xs font-medium text-white transition hover:bg-[#ba4547] disabled:cursor-not-allowed disabled:opacity-50"
            >
              {creatingSession ? (
                <IconLoader className="h-5 w-5 animate-spin" />
              ) : (
                <IconPlus className="h-5 w-5" />
              )}
              <span>{creatingSession ? "Creating..." : "New chat"}</span>
            </button>
          </div>
        </SidebarHeader>

        <SidebarContent className="bg-[#050505] px-2 py-3">
          {error && (
            <div className="mx-2 mb-3 rounded-2xl border border-red-500/20 bg-red-500/10 p-3 text-xs text-red-200">
              <div>{error}</div>
              <button
                onClick={fetchChatSessions}
                className="mt-2 text-red-100 underline underline-offset-4"
                type="button"
              >
                Retry
              </button>
            </div>
          )}

          <SidebarGroup className="overflow-hidden">
            <SidebarGroupLabel className="flex items-center justify-between px-3 py-2 text-[10px] uppercase tracking-[0.18em] text-white/35">
              <span>Your chats</span>
              <button
                onClick={fetchChatSessions}
                className="rounded-md p-1 transition hover:bg-white/10"
                type="button"
              >
                <IconLoader
                  className={`h-3.5 w-3.5 text-white/45 ${
                    loading ? "animate-spin" : ""
                  }`}
                />
              </button>
            </SidebarGroupLabel>

            <SidebarGroupContent className="chat-scroll max-h-[calc(100vh-220px)] overflow-y-auto pr-1 overscroll-contain scroll-smooth">
              {loading && (
                <div className="py-8 text-center text-xs text-white/45">
                  Loading chats...
                </div>
              )}

              {!loading &&
                sortedSessions.map((session) => (
                  <ChatHistoryItem
                    key={session.id}
                    session={session}
                    isActive={session.id === activeSessionId}
                    onSelect={(id) => onSessionSelect?.(id)}
                    onDelete={handleDeleteChat}
                  />
                ))}

              {!loading && chatSessions.length === 0 && (
                <div className="py-8 text-center text-sm text-white/40">
                  No chat history found.
                </div>
              )}
            </SidebarGroupContent>
          </SidebarGroup>
        </SidebarContent>

        <SidebarFooter className="border-t border-white/10 bg-[#080808] p-3 text-center text-xs text-white/30">
          Session history
        </SidebarFooter>
      </Sidebar>
    );
  }
);

ChatSidebarMidwife.displayName = "ChatSidebarMidwife";